
// js/data.js — Static service data + localStorage helpers


const MOCK_SERVICES = [
  {
    id: '1',
    title: 'Luxury Hair Spa Treatment',
    category: 'Hair Care',
    provider: 'Élite Hair Studio',
    price: 2499,
    duration: 90,
    rating: 4.9,
    reviewCount: 128,
    image: 'https://images.unsplash.com/photo-1560869713-7d0a29430803?w=600&q=80',
    description: 'Indulge in a deep-nourishing hair spa that restores moisture, eliminates frizz, and leaves your hair silky smooth. Includes keratin mask, scalp massage, and blowout.',
    location: 'Connaught Place, Delhi',
    tags: ['trending', 'popular'],
  },
  {
    id: '2',
    title: 'Glow Facial & Skin Brightening',
    category: 'Skin Care',
    provider: 'Lumière Skin Clinic',
    price: 3199,
    duration: 60,
    rating: 4.8,
    reviewCount: 96,
    image: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=600&q=80',
    description: 'A signature brightening facial using vitamin C serums, hyaluronic acid, and LED therapy to reveal radiant, even-toned skin. Perfect for dull or stressed skin.',
    location: 'Bandra West, Mumbai',
    tags: ['popular', 'new'],
  },
  {
    id: '3',
    title: 'Nail Art & Gel Extension',
    category: 'Nail Art',
    provider: 'Gloss Nail Bar',
    price: 1299,
    duration: 75,
    rating: 4.7,
    reviewCount: 214,
    image: 'https://images.unsplash.com/photo-1604654894610-df63bc536371?w=600&q=80',
    description: 'Premium gel nail extensions with hand-painted art. Choose from 200+ designs. Includes cuticle care, nail shaping, and long-lasting finish guaranteed for 3 weeks.',
    location: 'Koramangala, Bangalore',
    tags: ['trending'],
  },
  {
    id: '4',
    title: 'Bridal Makeup & Draping',
    category: 'Makeup',
    provider: 'Aura Bridal Studio',
    price: 12999,
    duration: 180,
    rating: 5.0,
    reviewCount: 47,
    image: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=600&q=80',
    description: 'Full bridal transformation with HD airbrush makeup, saree/lehenga draping, hair styling, and accessories. Includes pre-bridal trial session.',
    location: 'Jubilee Hills, Hyderabad',
    tags: ['premium', 'popular'],
  },
  {
    id: '5',
    title: 'Swedish Deep Tissue Massage',
    category: 'Spa & Massage',
    provider: 'Serenity Wellness Spa',
    price: 1899,
    duration: 60,
    rating: 4.9,
    reviewCount: 183,
    image: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=600&q=80',
    description: 'Release tension and restore balance with our signature deep-tissue massage using warm aromatherapy oils. Targets chronic muscle pain and improves circulation.',
    location: 'Indiranagar, Bangalore',
    tags: ['popular'],
  },
  {
    id: '6',
    title: 'Microblading & Brow Sculpting',
    category: 'Eyebrows & Lashes',
    provider: 'Brow Architects',
    price: 4500,
    duration: 120,
    rating: 4.8,
    reviewCount: 62,
    image: 'https://images.unsplash.com/photo-1616394584738-fc6e612e71b9?w=600&q=80',
    description: 'Achieve perfect, natural-looking brows with precision microblading by certified artists. Includes consultation, numbing, shaping, and touch-up session.',
    location: 'Hauz Khas, Delhi',
    tags: ['new', 'premium'],
  },
  {
    id: '7',
    title: 'Vitamin Infusion Body Wrap',
    category: 'Wellness',
    provider: 'Pure Bliss Retreat',
    price: 2799,
    duration: 90,
    rating: 4.6,
    reviewCount: 39,
    image: 'https://images.unsplash.com/photo-1515377905703-c4788e51af15?w=600&q=80',
    description: 'Full-body detox wrap using antioxidant-rich clays and essential oils. Deeply hydrates skin, reduces bloating, and leaves skin soft and glowing.',
    location: 'Powai, Mumbai',
    tags: ['new'],
  },
  {
    id: '8',
    title: 'Men\'s Grooming & Beard Styling',
    category: 'Men Grooming',
    provider: 'The Gentleman\'s Den',
    price: 799,
    duration: 45,
    rating: 4.7,
    reviewCount: 291,
    image: 'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=600&q=80',
    description: 'Premium men\'s grooming experience: haircut, hot towel shave, beard sculpting, and scalp massage. Walk out looking sharp and feeling fresh.',
    location: 'Sector 18, Noida',
    tags: ['trending', 'popular'],
  },
  {
    id: '9',
    title: 'Eyelash Lift & Tint',
    category: 'Eyebrows & Lashes',
    provider: 'Lash Luxe Studio',
    price: 1599,
    duration: 60,
    rating: 4.8,
    reviewCount: 77,
    image: 'https://images.unsplash.com/photo-1589710751893-f9a6770ad71b?q=80&w=1974&auto=format&fit=crop',
    description: 'A game-changing lash lift that curls your natural lashes upward for 6-8 weeks, paired with a tint for dramatic, mascara-free eyes. Zero damage formula.',
    location: 'Andheri West, Mumbai',
    tags: ['popular'],
  },
  {
    id: '10',
    title: 'Hot Stone Chakra Balancing',
    category: 'Spa & Massage',
    provider: 'Zen Garden Spa',
    price: 3499,
    duration: 90,
    rating: 4.9,
    reviewCount: 54,
    image: 'https://images.unsplash.com/photo-1600334129128-685c5582fd35?w=600&q=80',
    description: 'Ancient healing ritual using volcanic basalt stones and chakra-aligned essential oils. Melts away stress, re-energizes your body, and soothes the mind.',
    location: 'Whitefield, Bangalore',
    tags: ['premium', 'trending'],
  },
  {
    id: '11',
    title: 'Keratin Smoothing Treatment',
    category: 'Hair Care',
    provider: 'Silk & Shine Salon',
    price: 5999,
    duration: 150,
    rating: 4.7,
    reviewCount: 103,
    image: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=600&q=80',
    description: 'Brazilian keratin treatment that eliminates frizz, adds brilliant shine, and makes hair 80% straighter for up to 4 months. Includes hydrating hair mask.',
    location: 'Salt Lake, Kolkata',
    tags: ['popular'],
  },
  {
    id: '12',
    title: 'Hydra Dermabrasion Facial',
    category: 'Skin Care',
    provider: 'Derma Glow Clinic',
    price: 4200,
    duration: 75,
    rating: 4.9,
    reviewCount: 88,
    image: 'https://images.unsplash.com/photo-1512290923902-8a9f81dc236c?w=600&q=80',
    description: 'Medical-grade hydradermabrasion that exfoliates, extracts, and hydrates simultaneously. Targets blackheads, fine lines, and uneven texture. Zero downtime.',
    location: 'Banjara Hills, Hyderabad',
    tags: ['new', 'trending'],
  },
  {
    id: '13',
    title: 'Organic Henna & Hair Coloring',
    category: 'Hair Care',
    provider: 'Green Leaf Salon',
    price: 1800,
    duration: 120,
    rating: 4.8,
    reviewCount: 45,
    image: 'https://images.unsplash.com/photo-1519735811561-bbda558dfa6a?w=600&q=80',
    description: '100% natural organic henna application for chemical-free hair coloring and deep conditioning. Leaves hair healthy, shiny, and naturally tinted.',
    location: 'GK-1, Delhi',
    tags: ['organic', 'new'],
  },
  {
    id: '14',
    title: 'Ayurvedic Full Body Abhyanga',
    category: 'Spa & Massage',
    provider: 'Veda Wellness Center',
    price: 2999,
    duration: 90,
    rating: 4.9,
    reviewCount: 32,
    image: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=600&q=80',
    description: 'Traditional Ayurvedic warm oil massage that balances the doshas, improves circulation, and promotes deep relaxation using herb-infused oils.',
    location: 'Rishikesh, Uttarakhand',
    tags: ['traditional', 'premium'],
  },
  {
    id: '15',
    title: 'Thai Yoga Massage',
    category: 'Spa & Massage',
    provider: 'The Zen Hub',
    price: 2199,
    duration: 75,
    rating: 4.7,
    reviewCount: 58,
    image: 'https://images.unsplash.com/photo-1519823551278-64ac92734fb1?w=600&q=80',
    description: 'Ancient healing system combining acupressure, Indian Ayurvedic principles, and assisted yoga postures. Improves flexibility and energy flow.',
    location: 'Vasant Kunj, Delhi',
    tags: ['popular'],
  },
  {
    id: '16',
    title: 'Luxury Pedicure with Paraffin Wax',
    category: 'Nail Art',
    provider: 'The Nail Boutique',
    price: 1499,
    duration: 60,
    rating: 4.8,
    reviewCount: 89,
    image: 'https://images.unsplash.com/photo-1519014816548-bf5fe059798b?w=600&q=80',
    description: 'Complete foot care including salt soak, scrub, mask, and paraffin wax treatment for baby-soft feet. Finished with premium gel polish.',
    location: 'Gurgaon, Sector 43',
    tags: ['trending'],
  },
  {
    id: '17',
    title: 'Party Makeup & Hair Styling',
    category: 'Makeup',
    provider: 'Glam Goddess',
    price: 4999,
    duration: 90,
    rating: 4.9,
    reviewCount: 112,
    image: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=600&q=80',
    description: 'Get ready for any special occasion with professional HD makeup and a custom hairstyle. Includes lash application and setting spray for all-night wear.',
    location: 'Colaba, Mumbai',
    tags: ['popular', 'trending'],
  },
  {
    id: '18',
    title: 'Acupuncture & Holistic Healing',
    category: 'Wellness',
    provider: 'Qi Wellness Clinic',
    price: 2500,
    duration: 60,
    rating: 4.6,
    reviewCount: 27,
    image: 'https://images.unsplash.com/photo-1512290902316-24e0303e9447?w=600&q=80',
    description: 'Expert acupuncture session to treat chronic pain, stress, and anxiety. Performed by licensed practitioners in a serene environment.',
    location: 'Nungambakkam, Chennai',
    tags: ['new', 'wellness'],
  },
  {
    id: '19',
    title: 'Teeth Whitening Express',
    category: 'Wellness',
    provider: 'Bright Smile Dental',
    price: 5500,
    duration: 45,
    rating: 4.8,
    reviewCount: 156,
    image: 'https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?w=600&q=80',
    description: 'Get a brighter smile in under an hour. Safe and effective professional teeth whitening that removes stains from coffee, tea, and tobacco.',
    location: 'Ahmadebad, Gujarat',
    tags: ['medical', 'premium'],
  },
  {
    id: '20',
    title: 'Anti-Pollution Detox Facial',
    category: 'Skin Care',
    provider: 'Urban Glow Studio',
    price: 2200,
    duration: 60,
    rating: 4.7,
    reviewCount: 74,
    image: 'https://images.unsplash.com/photo-1512290923902-8a9f81dc236c?w=600&q=80',
    description: 'Specifically designed for city dwellers, this facial uses charcoal and antioxidant masks to draw out pollutants and revitalize dull skin.',
    location: 'Okhla, Delhi',
    tags: ['new', 'trending'],
  },
  {
    id: '21',
    title: 'Laser Hair Removal (Trial)',
    category: 'Skin Care',
    provider: 'Smooth Skin Clinic',
    price: 1999,
    duration: 30,
    rating: 4.9,
    reviewCount: 204,
    image: 'https://images.unsplash.com/photo-1515377905703-c4788e51af15?w=600&q=80',
    description: 'Introductory session for pain-free laser hair removal. Choose one small area (underarms, chin, or upper lip) for your trial.',
    location: 'Panchsheel Park, Delhi',
    tags: ['medical', 'trending'],
  },
  {
    id: '22',
    title: 'Coffee Body Scrub & Polishing',
    category: 'Wellness',
    provider: 'Earth Spa',
    price: 1599,
    duration: 60,
    rating: 4.8,
    reviewCount: 42,
    image: 'https://images.unsplash.com/photo-1600334129128-685c5582fd35?w=600&q=80',
    description: 'Invigorating coffee bean scrub that exfoliates dead skin cells, reduces cellulite, and improves blood flow for smooth, polished skin.',
    location: 'HSR Layout, Bangalore',
    tags: ['popular'],
  },
  {
    id: '23',
    title: 'Professional Hair Extensions',
    category: 'Hair Care',
    provider: 'Volume Hair Bar',
    price: 8500,
    duration: 180,
    rating: 4.7,
    reviewCount: 38,
    image: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=600&q=80',
    description: 'Add length and volume with premium 100% human hair extensions. Choose from clip-ins, tape-ins, or micro-beads. Includes custom styling.',
    location: 'Model Town, Delhi',
    tags: ['premium', 'new'],
  },
  {
    id: '24',
    title: 'Reflexology Foot Massage',
    category: 'Spa & Massage',
    provider: 'Sole Comfort',
    price: 999,
    duration: 45,
    rating: 4.9,
    reviewCount: 167,
    image: 'https://images.unsplash.com/photo-1519415387722-a1c3bbef716c?w=600&q=80',
    description: 'Pressure point therapy on the feet that corresponds to different organs and systems in the body. Relieves stress and boosts overall wellness.',
    location: 'South Ex, Delhi',
    tags: ['popular', 'affordable'],
  },
  {
    id: '25',
    title: 'Aromatherapy Salt Glow',
    category: 'Spa & Massage',
    provider: 'Ocean Breeze Spa',
    price: 1899,
    duration: 60,
    rating: 4.8,
    reviewCount: 45,
    image: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=600&q=80',
    description: 'Full-body exfoliation using mineral-rich sea salts and essential oils. Removes dead skin and leaves your body feeling refreshed and glowing.',
    location: 'Hauz Khas, Delhi',
    tags: ['new', 'popular'],
  },
  {
    id: '26',
    title: 'Gel Polish Manicure',
    category: 'Nail Art',
    provider: 'Gloss & Glow',
    price: 899,
    duration: 45,
    rating: 4.7,
    reviewCount: 132,
    image: 'https://images.unsplash.com/photo-1604654894610-df63bc536371?w=600&q=80',
    description: 'Long-lasting gel manicure with over 100 colors to choose from. Includes nail shaping, cuticle care, and a shiny chip-free finish.',
    location: 'Saket, Delhi',
    tags: ['trending'],
  },
  {
    id: '27',
    title: 'Hollywood Glam Makeup',
    category: 'Makeup',
    provider: 'Star Studio',
    price: 3499,
    duration: 75,
    rating: 4.9,
    reviewCount: 64,
    image: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=600&q=80',
    description: 'Get red-carpet ready with high-definition makeup, contouring, and dramatic lashes. Perfect for evening events and photoshoots.',
    location: 'Bandra, Mumbai',
    tags: ['premium', 'trending'],
  },
  {
    id: '28',
    title: 'Anti-Aging Gold Facial',
    category: 'Skin Care',
    provider: 'Royal Skin Clinic',
    price: 4999,
    duration: 90,
    rating: 5.0,
    reviewCount: 28,
    image: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=600&q=80',
    description: 'Luxury 24K gold facial that stimulates collagen, reduces fine lines, and firms the skin. Experience the ultimate in anti-aging luxury.',
    location: 'Jubilee Hills, Hyderabad',
    tags: ['premium', 'new'],
  },
  {
    id: '29',
    title: 'Scalp Detox & Rejuvenation',
    category: 'Hair Care',
    provider: 'Root & Stem',
    price: 1599,
    duration: 60,
    rating: 4.8,
    reviewCount: 52,
    image: 'https://images.unsplash.com/photo-1560869713-7d0a29430803?w=600&q=80',
    description: 'Deep cleansing scalp treatment that removes product buildup and promotes healthy hair growth. Includes a relaxing scalp massage.',
    location: 'Indiranagar, Bangalore',
    tags: ['popular'],
  },
  {
    id: '30',
    title: 'Volcanic Clay Body Mask',
    category: 'Wellness',
    provider: 'Earth Elements',
    price: 2499,
    duration: 75,
    rating: 4.7,
    reviewCount: 39,
    image: 'https://images.unsplash.com/photo-1515377905703-c4788e51af15?w=600&q=80',
    description: 'Detoxifying body wrap using mineral-rich volcanic clay. Draws out impurities and replenishes the skin with essential minerals.',
    location: 'Pune, Maharashtra',
    tags: ['new'],
  },
  {
    id: '31',
    title: 'Under-Eye Brightening Treatment',
    category: 'Skin Care',
    provider: 'Lash & Lite',
    price: 1200,
    duration: 30,
    rating: 4.6,
    reviewCount: 88,
    image: 'https://images.unsplash.com/photo-15122290923902-8a9f81dc236c?w=600&q=80',
    description: 'Targeted treatment to reduce dark circles and puffiness. Uses cooling masks and caffeine serums for an instant refreshed look.',
    location: 'Cyber City, Gurgaon',
    tags: ['trending'],
  },
  {
    id: '32',
    title: 'Balayage Hair Highlighting',
    category: 'Hair Care',
    provider: 'Color Theory',
    price: 6500,
    duration: 180,
    rating: 4.9,
    reviewCount: 47,
    image: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=600&q=80',
    description: 'Natural-looking, sun-kissed hair highlights hand-painted by our master colorists. Includes toner and deep conditioning treatment.',
    location: 'Vasant Vihar, Delhi',
    tags: ['premium', 'trending'],
  },
  {
    id: '33',
    title: 'Sports Massage (Deep Tissue)',
    category: 'Spa & Massage',
    provider: 'Active Recovery',
    price: 2299,
    duration: 90,
    rating: 4.8,
    reviewCount: 115,
    image: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=600&q=80',
    description: 'Intense deep-tissue massage designed for athletes and active individuals. Relieves muscle soreness and improves range of motion.',
    location: 'Whitefield, Bangalore',
    tags: ['popular'],
  },
  {
    id: '34',
    title: 'Brow Lamination & Shape',
    category: 'Eyebrows & Lashes',
    provider: 'Arch Angels',
    price: 1800,
    duration: 60,
    rating: 4.7,
    reviewCount: 92,
    image: 'https://images.unsplash.com/photo-1616394584738-fc6e612e71b9?w=600&q=80',
    description: 'Straightens and lifts brow hairs for a fuller, more groomed look. Includes brow shaping and tinting for a perfect finish.',
    location: 'Chandigarh',
    tags: ['trending', 'new'],
  },
  {
    id: '35',
    title: 'Luxury Foot Soak & Scrub',
    category: 'Spa & Massage',
    provider: 'Sole Sanctuary',
    price: 799,
    duration: 30,
    rating: 4.8,
    reviewCount: 156,
    image: 'https://images.unsplash.com/photo-1519415387722-a1c3bbef716c?w=600&q=80',
    description: 'Relaxing foot soak with essential oils followed by a revitalizing sugar scrub and mini massage. The perfect quick pampering session.',
    location: 'Koramangala, Bangalore',
    tags: ['affordable'],
  },
  {
    id: '36',
    title: 'Express Glow Facial',
    category: 'Skin Care',
    provider: 'Radiance Bar',
    price: 1499,
    duration: 30,
    rating: 4.7,
    reviewCount: 210,
    image: 'https://images.unsplash.com/photo-1512290923902-8a9f81dc236c?w=600&q=80',
    description: 'Fast and effective facial treatment for those on the go. Includes deep cleansing, exfoliation, and a vitamin-infused glow mask.',
    location: 'DLF Phase 3, Gurgaon',
    tags: ['popular', 'affordable'],
  },
];

let SERVICES = [...MOCK_SERVICES];
// API Configuration
const API_URL = 'http://localhost:5000/api';

async function loadServices() {
  try {
    const res = await fetch(`${API_URL}/services?limit=50`);
    const data = await res.json();
    if (data.success && data.services && data.services.length > 0) {
      // Map _id to id so frontend template variables stay intact
      SERVICES = data.services.map(s => ({ ...s, id: s._id || s.id }));
    }
  } catch (e) {
    console.log('Using mock services (Backend unavailable)');
  }
  return SERVICES;
}

const CATEGORIES = [
  { id: 'all', label: 'All Services', icon: '✨', image: '' },
  { id: 'Hair Care', label: 'Hair Care', icon: '💇', image: 'https://images.unsplash.com/photo-1560869713-7d0a29430803?w=400&q=80' },
  { id: 'Skin Care', label: 'Skin Care', icon: '🌿', image: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=400&q=80' },
  { id: 'Nail Art', label: 'Nail Art', icon: '💅', image: 'https://images.unsplash.com/photo-1604654894610-df63bc536371?w=400&q=80' },
  { id: 'Makeup', label: 'Makeup', icon: '💄', image: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=400&q=80' },
  { id: 'Spa & Massage', label: 'Spa & Massage', icon: '🧘', image: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=400&q=80' },
  { id: 'Eyebrows & Lashes', label: 'Brows & Lashes', icon: '👁️', image: 'https://images.unsplash.com/photo-1589710751893-f9a6770ad71b?q=80&w=1974&auto=format&fit=crop' },
  { id: 'Wellness', label: 'Wellness', icon: '🌸', image: 'https://images.unsplash.com/photo-1515377905703-c4788e51af15?w=400&q=80' },
  { id: 'Men Grooming', label: 'Men Grooming', icon: '🪒', image: 'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=400&q=80' },
];

// ── LocalStorage helpers ────────────────────────────────────
const LS = {
  get: (k, fb = []) => { try { return JSON.parse(localStorage.getItem(k)) ?? fb; } catch { return fb; } },
  set: (k, v) => localStorage.setItem(k, JSON.stringify(v)),
  push: (k, item) => { const arr = LS.get(k); arr.push(item); LS.set(k, arr); },
};

// Bookings
function getBookings() { return LS.get('aura_bookings', []); }
function saveBooking(b) { LS.push('aura_bookings', b); }
function cancelBooking(id) {
  const all = getBookings().map(b => b.id === id ? { ...b, status: 'cancelled' } : b);
  LS.set('aura_bookings', all);
}

// Reviews
function getReviews(serviceId) { return LS.get(`aura_reviews_${serviceId}`, []); }
function saveReview(serviceId, r) { LS.push(`aura_reviews_${serviceId}`, r); }

// Auth & JWT Handlers
function getToken() { return localStorage.getItem('aura_token'); }
function getUser() { return LS.get('aura_user', null); }

function setUser(user, token) {
  LS.set('aura_user', user);
  if (token) localStorage.setItem('aura_token', token);
}

function logoutUser() {
  localStorage.removeItem('aura_user');
  localStorage.removeItem('aura_token');
}

function isLoggedIn() { return !!getToken(); }
